<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_hotel extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_hotel_model');
    } 

    /*
     * Listing of tbl_hotel
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_hotel/index?');
        $config['total_rows'] = $this->Tbl_hotel_model->get_all_tbl_hotel_count();
        $this->pagination->initialize($config);

        $data['tbl_hotel'] = $this->Tbl_hotel_model->get_all_tbl_hotel($params);
        
        $data['_view'] = 'hotel/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_hotel
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_hotel','Nama Hotel','required');
		$this->form_validation->set_rules('latitude','Latitude','required');
		$this->form_validation->set_rules('longitude','Longitude','required');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('alamat','Alamat','required');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_hotel' => $this->input->post('nama_hotel'),
				'latitude' => $this->input->post('latitude'),
				'longitude' => $this->input->post('longitude'),
				'created_at' => $this->input->post('created_at'),
				'update_at' => $this->input->post('update_at'),
				'alamat' => $this->input->post('alamat'),
				'description' => $this->input->post('description'),
            );
            
            $tbl_hotel_id = $this->Tbl_hotel_model->add_tbl_hotel($params);
            redirect('tbl_hotel/index');
        }
        else
        {            
            $data['_view'] = 'hotel/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_hotel
     */
    function edit($id_hotel)
    {   
        // check if the tbl_hotel exists before trying to edit it
        $data['tbl_hotel'] = $this->Tbl_hotel_model->get_tbl_hotel($id_hotel);
        
        if(isset($data['tbl_hotel']['id_hotel']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_hotel','Nama Hotel','required');
			$this->form_validation->set_rules('latitude','Latitude','required');
			$this->form_validation->set_rules('longitude','Longitude','required');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('alamat','Alamat','required');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_hotel' => $this->input->post('nama_hotel'),
					'latitude' => $this->input->post('latitude'),
					'longitude' => $this->input->post('longitude'),
					'created_at' => $this->input->post('created_at'),
					'update_at' => $this->input->post('update_at'),
					'alamat' => $this->input->post('alamat'),
					'description' => $this->input->post('description'),
                );

                $this->Tbl_hotel_model->update_tbl_hotel($id_hotel,$params);            
                redirect('tbl_hotel/index');
            }
            else
            {
                $data['_view'] = 'hotel/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_hotel you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_hotel
     */
    function remove($id_hotel)
    {
        $tbl_hotel = $this->Tbl_hotel_model->get_tbl_hotel($id_hotel);

        // check if the tbl_hotel exists before trying to delete it
        if(isset($tbl_hotel['id_hotel']))
        {
            $this->Tbl_hotel_model->delete_tbl_hotel($id_hotel);
            redirect('tbl_hotel/index');
        }
        else
            show_error('The tbl_hotel you are trying to delete does not exist.');
    }
    
}
