<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_article extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_article_model');
    } 

    /*
     * Listing of tbl_article
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_article/index?');
        $config['total_rows'] = $this->Tbl_article_model->get_all_tbl_article_count();
        $this->pagination->initialize($config);

        $data['tbl_article'] = $this->Tbl_article_model->get_all_tbl_article($params);
        
        $data['_view'] = 'article/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_article
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('judul_article','Judul Article','required');
		$this->form_validation->set_rules('jenis_article','Jenis Article','required');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('penulis','Penulis','required');
		$this->form_validation->set_rules('image','Image','required');
		$this->form_validation->set_rules('isi_article','Isi Article','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'jenis_article' => $this->input->post('jenis_article'),
				'judul_article' => $this->input->post('judul_article'),
				'created_at' => $this->input->post('created_at'),
				'update_at' => $this->input->post('update_at'),
				'penulis' => $this->input->post('penulis'),
				'image' => $this->input->post('image'),
				'isi_article' => $this->input->post('isi_article'),
            );
            
            $tbl_article_id = $this->Tbl_article_model->add_tbl_article($params);
            redirect('tbl_article/index');
        }
        else
        {            
            $data['_view'] = 'article/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_article
     */
    function edit($id_article)
    {   
        // check if the tbl_article exists before trying to edit it
        $data['tbl_article'] = $this->Tbl_article_model->get_tbl_article($id_article);
        
        if(isset($data['tbl_article']['id_article']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('judul_article','Judul Article','required');
			$this->form_validation->set_rules('jenis_article','Jenis Article','required');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('penulis','Penulis','required');
			$this->form_validation->set_rules('image','Image','required');
			$this->form_validation->set_rules('isi_article','Isi Article','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'jenis_article' => $this->input->post('jenis_article'),
					'judul_article' => $this->input->post('judul_article'),
					'created_at' => $this->input->post('created_at'),
					'update_at' => $this->input->post('update_at'),
					'penulis' => $this->input->post('penulis'),
					'image' => $this->input->post('image'),
					'isi_article' => $this->input->post('isi_article'),
                );

                $this->Tbl_article_model->update_tbl_article($id_article,$params);            
                redirect('tbl_article/index');
            }
            else
            {
                $data['_view'] = 'article/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_article you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_article
     */
    function remove($id_article)
    {
        $tbl_article = $this->Tbl_article_model->get_tbl_article($id_article);

        // check if the tbl_article exists before trying to delete it
        if(isset($tbl_article['id_article']))
        {
            $this->Tbl_article_model->delete_tbl_article($id_article);
            redirect('tbl_article/index');
        }
        else
            show_error('The tbl_article you are trying to delete does not exist.');
    }
    
}
