<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_leader_camp extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_leader_camp_model');
    } 

    /*
     * Listing of tbl_leader_camp
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_leader_camp/index?');
        $config['total_rows'] = $this->Tbl_leader_camp_model->get_all_tbl_leader_camp_count();
        $this->pagination->initialize($config);

        $data['tbl_leader_camp'] = $this->Tbl_leader_camp_model->get_all_tbl_leader_camp($params);
        
        $data['_view'] = 'leader_camp/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_leader_camp
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_paket','Nama Paket','required');
		$this->form_validation->set_rules('price','Price','required');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('location_leader_camp','Location Leader Camp','required');
		$this->form_validation->set_rules('image','Image','required');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_paket' => $this->input->post('nama_paket'),
				'price' => $this->input->post('price'),
				'created_at' => $this->input->post('created_at'),
				'update_at' => $this->input->post('update_at'),
				'location_leader_camp' => $this->input->post('location_leader_camp'),
				'image' => $this->input->post('image'),
				'description' => $this->input->post('description'),
            );
            
            $tbl_leader_camp_id = $this->Tbl_leader_camp_model->add_tbl_leader_camp($params);
            redirect('tbl_leader_camp/index');
        }
        else
        {            
            $data['_view'] = 'leader_camp/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_leader_camp
     */
    function edit($id_leader_camp)
    {   
        // check if the tbl_leader_camp exists before trying to edit it
        $data['tbl_leader_camp'] = $this->Tbl_leader_camp_model->get_tbl_leader_camp($id_leader_camp);
        
        if(isset($data['tbl_leader_camp']['id_leader_camp']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_paket','Nama Paket','required');
			$this->form_validation->set_rules('price','Price','required');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('location_leader_camp','Location Leader Camp','required');
			$this->form_validation->set_rules('image','Image','required');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_paket' => $this->input->post('nama_paket'),
					'price' => $this->input->post('price'),
					'created_at' => $this->input->post('created_at'),
					'update_at' => $this->input->post('update_at'),
					'location_leader_camp' => $this->input->post('location_leader_camp'),
					'image' => $this->input->post('image'),
					'description' => $this->input->post('description'),
                );

                $this->Tbl_leader_camp_model->update_tbl_leader_camp($id_leader_camp,$params);            
                redirect('tbl_leader_camp/index');
            }
            else
            {
                $data['_view'] = 'leader_camp/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_leader_camp you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_leader_camp
     */
    function remove($id_leader_camp)
    {
        $tbl_leader_camp = $this->Tbl_leader_camp_model->get_tbl_leader_camp($id_leader_camp);

        // check if the tbl_leader_camp exists before trying to delete it
        if(isset($tbl_leader_camp['id_leader_camp']))
        {
            $this->Tbl_leader_camp_model->delete_tbl_leader_camp($id_leader_camp);
            redirect('tbl_leader_camp/index');
        }
        else
            show_error('The tbl_leader_camp you are trying to delete does not exist.');
    }
    
}
