<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_car extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_car_model');
    } 

    /*
     * Listing of tbl_car
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_car/index?');
        $config['total_rows'] = $this->Tbl_car_model->get_all_tbl_car_count();
        $this->pagination->initialize($config);

        $data['tbl_car'] = $this->Tbl_car_model->get_all_tbl_car($params);
        
        $data['_view'] = 'rent_car/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_car
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_kendaraan','Nama Kendaraan','required');
		$this->form_validation->set_rules('harga','Harga','required');
		$this->form_validation->set_rules('promo','Promo','required');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_kendaraan' => $this->input->post('nama_kendaraan'),
				'harga' => $this->input->post('harga'),
				'promo' => $this->input->post('promo'),
				'created_at' => $this->input->post('created_at'),
				'update_at' => $this->input->post('update_at'),
				'description' => $this->input->post('description'),
            );
            
            $tbl_car_id = $this->Tbl_car_model->add_tbl_car($params);
            redirect('tbl_car/index');
        }
        else
        {            
            $data['_view'] = 'rent_car/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_car
     */
    function edit($id_car)
    {   
        // check if the tbl_car exists before trying to edit it
        $data['tbl_car'] = $this->Tbl_car_model->get_tbl_car($id_car);
        
        if(isset($data['tbl_car']['id_car']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_kendaraan','Nama Kendaraan','required');
			$this->form_validation->set_rules('harga','Harga','required');
			$this->form_validation->set_rules('promo','Promo','required');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_kendaraan' => $this->input->post('nama_kendaraan'),
					'harga' => $this->input->post('harga'),
					'promo' => $this->input->post('promo'),
					'created_at' => $this->input->post('created_at'),
					'update_at' => $this->input->post('update_at'),
					'description' => $this->input->post('description'),
                );

                $this->Tbl_car_model->update_tbl_car($id_car,$params);            
                redirect('tbl_car/index');
            }
            else
            {
                $data['_view'] = 'rent_car/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_car you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_car
     */
    function remove($id_car)
    {
        $tbl_car = $this->Tbl_car_model->get_tbl_car($id_car);

        // check if the tbl_car exists before trying to delete it
        if(isset($tbl_car['id_car']))
        {
            $this->Tbl_car_model->delete_tbl_car($id_car);
            redirect('tbl_car/index');
        }
        else
            show_error('The tbl_car you are trying to delete does not exist.');
    }
    
}
