<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_order extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_order_model');
    } 

    /*
     * Listing of tbl_order
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_order/index?');
        $config['total_rows'] = $this->Tbl_order_model->get_all_tbl_order_count();
        $this->pagination->initialize($config);

        $data['tbl_order'] = $this->Tbl_order_model->get_all_tbl_order($params);
        
        $data['_view'] = 'order/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_order
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('order_name','Order Name','required');
		$this->form_validation->set_rules('order_type','Order Type','required');
		$this->form_validation->set_rules('nama','Nama','required');
		$this->form_validation->set_rules('alamat','Alamat','required');
		$this->form_validation->set_rules('no_telp','No Telp','required');
		$this->form_validation->set_rules('email','Email','required|valid_email');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('keterangan','Keterangan','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'order_type' => $this->input->post('order_type'),
				'order_name' => $this->input->post('order_name'),
				'nama' => $this->input->post('nama'),
				'alamat' => $this->input->post('alamat'),
				'no_telp' => $this->input->post('no_telp'),
				'email' => $this->input->post('email'),
				'created_at' => $this->input->post('created_at'),
				'update_at' => $this->input->post('update_at'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $tbl_order_id = $this->Tbl_order_model->add_tbl_order($params);
            redirect('tbl_order/index');
        }
        else
        {            
            $data['_view'] = 'order/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_order
     */
    function edit($id_order)
    {   
        // check if the tbl_order exists before trying to edit it
        $data['tbl_order'] = $this->Tbl_order_model->get_tbl_order($id_order);
        
        if(isset($data['tbl_order']['id_order']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('order_name','Order Name','required');
			$this->form_validation->set_rules('order_type','Order Type','required');
			$this->form_validation->set_rules('nama','Nama','required');
			$this->form_validation->set_rules('alamat','Alamat','required');
			$this->form_validation->set_rules('no_telp','No Telp','required');
			$this->form_validation->set_rules('email','Email','required|valid_email');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('keterangan','Keterangan','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'order_type' => $this->input->post('order_type'),
					'order_name' => $this->input->post('order_name'),
					'nama' => $this->input->post('nama'),
					'alamat' => $this->input->post('alamat'),
					'no_telp' => $this->input->post('no_telp'),
					'email' => $this->input->post('email'),
					'created_at' => $this->input->post('created_at'),
					'update_at' => $this->input->post('update_at'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Tbl_order_model->update_tbl_order($id_order,$params);            
                redirect('tbl_order/index');
            }
            else
            {
                $data['_view'] = 'order/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_order you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_order
     */
    function remove($id_order)
    {
        $tbl_order = $this->Tbl_order_model->get_tbl_order($id_order);

        // check if the tbl_order exists before trying to delete it
        if(isset($tbl_order['id_order']))
        {
            $this->Tbl_order_model->delete_tbl_order($id_order);
            redirect('tbl_order/index');
        }
        else
            show_error('The tbl_order you are trying to delete does not exist.');
    }
    
}
