<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_adventure_tour extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tbl_adventure_tour_model');
    } 

    /*
     * Listing of tbl_adventure_tour
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tbl_adventure_tour/index?');
        $config['total_rows'] = $this->Tbl_adventure_tour_model->get_all_tbl_adventure_tour_count();
        $this->pagination->initialize($config);

        $data['tbl_adventure_tour'] = $this->Tbl_adventure_tour_model->get_all_tbl_adventure_tour($params);
        
        $data['_view'] = 'adventure_tour/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tbl_adventure_tour
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama_paket','Nama Paket','required');
		$this->form_validation->set_rules('price','Price','required');
		$this->form_validation->set_rules('created_at','Created At','required');
		$this->form_validation->set_rules('location_adventure_tour','Location Adventure Tour','required');
		$this->form_validation->set_rules('image','Image','required');
		$this->form_validation->set_rules('description','Description','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama_paket' => $this->input->post('nama_paket'),
				'price' => $this->input->post('price'),
				'created_at' => $this->input->post('created_at'),
				'update_at' => $this->input->post('update_at'),
				'location_adventure_tour' => $this->input->post('location_adventure_tour'),
				'image' => $this->input->post('image'),
				'description' => $this->input->post('description'),
            );
            
            $tbl_adventure_tour_id = $this->Tbl_adventure_tour_model->add_tbl_adventure_tour($params);
            redirect('tbl_adventure_tour/index');
        }
        else
        {            
            $data['_view'] = 'adventure_tour/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tbl_adventure_tour
     */
    function edit($id_adventure_tour)
    {   
        // check if the tbl_adventure_tour exists before trying to edit it
        $data['tbl_adventure_tour'] = $this->Tbl_adventure_tour_model->get_tbl_adventure_tour($id_adventure_tour);
        
        if(isset($data['tbl_adventure_tour']['id_adventure_tour']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama_paket','Nama Paket','required');
			$this->form_validation->set_rules('price','Price','required');
			$this->form_validation->set_rules('created_at','Created At','required');
			$this->form_validation->set_rules('location_adventure_tour','Location Adventure Tour','required');
			$this->form_validation->set_rules('image','Image','required');
			$this->form_validation->set_rules('description','Description','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama_paket' => $this->input->post('nama_paket'),
					'price' => $this->input->post('price'),
					'created_at' => $this->input->post('created_at'),
					'update_at' => $this->input->post('update_at'),
					'location_adventure_tour' => $this->input->post('location_adventure_tour'),
					'image' => $this->input->post('image'),
					'description' => $this->input->post('description'),
                );

                $this->Tbl_adventure_tour_model->update_tbl_adventure_tour($id_adventure_tour,$params);            
                redirect('tbl_adventure_tour/index');
            }
            else
            {
                $data['_view'] = 'adventure_tour/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tbl_adventure_tour you are trying to edit does not exist.');
    } 

    /*
     * Deleting tbl_adventure_tour
     */
    function remove($id_adventure_tour)
    {
        $tbl_adventure_tour = $this->Tbl_adventure_tour_model->get_tbl_adventure_tour($id_adventure_tour);

        // check if the tbl_adventure_tour exists before trying to delete it
        if(isset($tbl_adventure_tour['id_adventure_tour']))
        {
            $this->Tbl_adventure_tour_model->delete_tbl_adventure_tour($id_adventure_tour);
            redirect('tbl_adventure_tour/index');
        }
        else
            show_error('The tbl_adventure_tour you are trying to delete does not exist.');
    }
    
}
