<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_car_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_car by id_car
     */
    function get_tbl_car($id_car)
    {
        return $this->db->get_where('tbl_car',array('id_car'=>$id_car))->row_array();
    }
    
    /*
     * Get all tbl_car count
     */
    function get_all_tbl_car_count()
    {
        $this->db->from('tbl_car');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_car
     */
    function get_all_tbl_car($params = array())
    {
        $this->db->order_by('id_car', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_car')->result_array();
    }
        
    /*
     * function to add new tbl_car
     */
    function add_tbl_car($params)
    {
        $this->db->insert('tbl_car',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_car
     */
    function update_tbl_car($id_car,$params)
    {
        $this->db->where('id_car',$id_car);
        return $this->db->update('tbl_car',$params);
    }
    
    /*
     * function to delete tbl_car
     */
    function delete_tbl_car($id_car)
    {
        return $this->db->delete('tbl_car',array('id_car'=>$id_car));
    }
}
