<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_hotel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_hotel by id_hotel
     */
    function get_tbl_hotel($id_hotel)
    {
        return $this->db->get_where('tbl_hotel',array('id_hotel'=>$id_hotel))->row_array();
    }
    
    /*
     * Get all tbl_hotel count
     */
    function get_all_tbl_hotel_count()
    {
        $this->db->from('tbl_hotel');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_hotel
     */
    function get_all_tbl_hotel($params = array())
    {
        $this->db->order_by('id_hotel', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_hotel')->result_array();
    }
        
    /*
     * function to add new tbl_hotel
     */
    function add_tbl_hotel($params)
    {
        $this->db->insert('tbl_hotel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_hotel
     */
    function update_tbl_hotel($id_hotel,$params)
    {
        $this->db->where('id_hotel',$id_hotel);
        return $this->db->update('tbl_hotel',$params);
    }
    
    /*
     * function to delete tbl_hotel
     */
    function delete_tbl_hotel($id_hotel)
    {
        return $this->db->delete('tbl_hotel',array('id_hotel'=>$id_hotel));
    }
}
