<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tbl_order_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tbl_order by id_order
     */
    function get_tbl_order($id_order)
    {
        return $this->db->get_where('tbl_order',array('id_order'=>$id_order))->row_array();
    }
    
    /*
     * Get all tbl_order count
     */
    function get_all_tbl_order_count()
    {
        $this->db->from('tbl_order');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tbl_order
     */
    function get_all_tbl_order($params = array())
    {
        $this->db->order_by('id_order', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tbl_order')->result_array();
    }
        
    /*
     * function to add new tbl_order
     */
    function add_tbl_order($params)
    {
        $this->db->insert('tbl_order',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tbl_order
     */
    function update_tbl_order($id_order,$params)
    {
        $this->db->where('id_order',$id_order);
        return $this->db->update('tbl_order',$params);
    }
    
    /*
     * function to delete tbl_order
     */
    function delete_tbl_order($id_order)
    {
        return $this->db->delete('tbl_order',array('id_order'=>$id_order));
    }
}
